export const CLOSE_TEACHERS_REQUEST = "CLOSE_TEACHERS_REQUEST"
export const CLOSE_TEACHERS_SUCCESS = "CLOSE_TEACHERS_SUCCESS"
export const CLOSE_TEACHERS_FAIL = "CLOSE_TEACHERS_FAIL"
export const CLOSE_TEACHERS_UPDATE = "CLOSE_TEACHERS_UPDATE"


export const MY_TEACHERS_REQUEST = "MY_TEACHERS_REQUEST"
export const MY_TEACHERS_SUCCESS = "MY_TEACHERS_SUCCESS"
export const MY_TEACHERS_FAIL = "MY_TEACHERS_FAIL"
export const MY_TEACHERS_UPDATE = "MY_TEACHERS_UPDATE"


export const TEACHER_REQUEST = "TEACHER_REQUEST"
export const TEACHER_SUCCESS = "TEACHER_SUCCESS"
export const TEACHER_FAIL = "TEACHER_FAIL"